<?php

// This file is automatically generated and modified by phpMyBackupPro v.2.1

$CONF['lang']="italian";
$CONF['import_error']="1";
$CONF['no_login']="0";
$CONF['login']="0";
$CONF['dir_backup']="0";
$CONF['dir_rec']="1";
$CONF['email_use']="0";
$CONF['email']="";
$CONF['ftp_use']="0";
$CONF['ftp_pasv']="1";
$CONF['ftp_del']="1";
$CONF['ftp_server']="";
$CONF['ftp_user']="";
$CONF['ftp_passwd']="";
$CONF['ftp_path']="";
$CONF['ftp_port']="21";
$CONF['sitename']="Syntax Desktop Demo";
$CONF['sql_passwd']="lppfeqdk";
$CONF['sql_host']="localhost";
$CONF['sql_user']="schiavotto";
$CONF['sql_db']="schiavotto";
$CONF['date']="%x %X";
$CONF['del_time']="";
$CONF['del_number']="5";
$CONF['timelimit']="60";
$CONF['confirm']="1";
$CONF['stylesheet']="standard";

$PMBP_SYS_VAR['last_scheduled']="";
$PMBP_SYS_VAR['this_login']="";
$PMBP_SYS_VAR['last_login']="";
$PMBP_SYS_VAR['dir_lists']="1";
$PMBP_SYS_VAR['memory_limit']="38000000";
$PMBP_SYS_VAR['except_tables']="";
$PMBP_SYS_VAR['scheduled_debug']="0";
$PMBP_SYS_VAR['schedule_all_dbs']="0";
$PMBP_SYS_VAR['ftp_timeout']="10";
$PMBP_SYS_VAR['dir_email_backup']="0";
$PMBP_SYS_VAR['F_dbs']="schiavotto";
$PMBP_SYS_VAR['F_comment']="";
$PMBP_SYS_VAR['F_tables']="on";
$PMBP_SYS_VAR['F_data']="on";
$PMBP_SYS_VAR['F_drop']="on";
$PMBP_SYS_VAR['F_compression']="";
$PMBP_SYS_VAR['F_ftp_dirs']="";
$PMBP_SYS_VAR['F_ftp_dirs_2']="";
$PMBP_SYS_VAR['F_packed']="";
$PMBP_SYS_VAR['F_updates']="0";
$PMBP_SYS_VAR['F_ffadd']="1";
$PMBP_SYS_VAR['EXS_scheduled_file']="???.php";
$PMBP_SYS_VAR['EXS_scheduled_dir']="0";
$PMBP_SYS_VAR['EXS_period']="";
$PMBP_SYS_VAR['security_key']="858df3a7c3cce4f9abd0def896b9c729";

?>